config/routes.rb
Rails.application.routes.draw do
  root 'fileuploads#new'
  post 'fileuploads/import_data'
  post 'fileuploads/find_attributes'
  post 'fileuploads/compare'
  resources :fileuploads

end

app/models/fileupload.rb
class Fileupload < ActiveRecord::Base

end

app/models/makemodel.rb
class Makemodel < ActiveRecord::Migration
  def self.import(file,project_name,file_name,start_row,end_row,unique,last_column)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(start_row.to_i)
    i=0
    header.count.times do
      unless header[i].nil?
        header[i]= header[i].gsub(/[^0-9A-Za-z]/, '').downcase
      end
      i+=1
    end
    name = "#{project_name.downcase}"+"#{file_name.downcase}"
    create_table name.pluralize do |t|
      header.each do |head|
        t.string head
      end
    end
    model_file = File.join("app", "models", name.singularize+".rb")
    model_name = name.singularize.capitalize
    File.open(model_file, "w+") do |f|
      f << "class #{model_name} < ActiveRecord::Base\nend"
    end

    ((start_row.to_i+1)..end_row.to_i).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      #should find a logic to find the model class that is being created
      product = Object.const_get(name.capitalize).new
      product.attributes = row.to_hash
      product.save!
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
      when ".csv" then Csv.new(file.path, nil, :ignore)
      when ".xls" then Roo::Excel.new(file.path)
      when ".xlsx" then Roo::Excelx.new(file.path)
      else raise "Unknown file type: #{file.original_filename}"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fileuploads_controller.rb
class FileuploadsController < ApplicationController
  before_action :set_fileupload, only: [:show, :edit, :update, :destroy] , except: [:find_attributes , :compare]

  # GET /fileuploads
  # GET /fileuploads.json
  def index
    @fileuploads = Fileupload.all
  end

  # GET /fileuploads/1
  # GET /fileuploads/1.json
  def show

  end

  def find_attributes
    @source_attributes = Object.const_get(params[:source]).attribute_names
    @target_attributes = Object.const_get(params[:target]).attribute_names
    render layout: nil
  end

  def compare
    @source_attributes = Object.const_get(params[:source]).select(params[:source_attribute],"empid","employeename").all
    @target_attributes = Object.const_get(params[:target]).select(params[:target_attribute],"empid","employeename").all
    render layout: nil
  end
  # GET /fileuploads/new
  def new
    @fileupload = Fileupload.new
  end

  # GET /fileuploads/1/edit
  def edit
  end

  # POST /fileuploads
  # POST /fileuploads.json
  def create
    @fileupload = Fileupload.new
    @fileupload.project_name = params[:project_name]
    @fileupload.file_name = params[:file_name]
    @fileupload.start = params[:start]
    @fileupload.end = params[:end]
    @fileupload.unique = params[:unique]
    @fileupload.last_row = params[:last_row]
    Makemodel.import(params[:excel_file],params[:project_name],params[:file_name],params[:start],params[:end],params[:unique],params[:last_row])


    respond_to do |format|
      if @fileupload.save
        format.html { redirect_to @fileupload, notice: 'Fileupload was successfully created.' }
        format.json { render :show, status: :created, location: @fileupload }
      else
        format.html { render :new }
        format.json { render json: @fileupload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fileuploads/1
  # PATCH/PUT /fileuploads/1.json
  def update
    respond_to do |format|
      if @fileupload.update(fileupload_params)
        format.html { redirect_to @fileupload, notice: 'Fileupload was successfully updated.' }
        format.json { render :show, status: :ok, location: @fileupload }
      else
        format.html { render :edit }
        format.json { render json: @fileupload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fileuploads/1
  # DELETE /fileuploads/1.json
  def destroy
    @fileupload.destroy
    respond_to do |format|
      format.html { redirect_to fileuploads_url, notice: 'Fileupload was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fileupload
      @fileupload = Fileupload.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fileupload_params
      params.require(:fileupload).permit(:project_name, :file_name, :start, :end, :unique, :last_row , :excel_file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fileuploads_helper.rb
module FileuploadsHelper
end

app/views/fileuploads/compare.html.erb
<script>
  $(document).ready(function(){
    $('#compareison_table').DataTable();
  });
</script>
<table id="compareison_table" >
  <thead>
  <tr>
    <td>Employee Id</td>
    <td>Employee Name</td>
    <td>Source value:<%=params[:source_attribute]%></td>
    <td>Target value:<%=params[:target_attribute]%></td>
  </tr>
  </thead>
  <boby>
    <%@source_attributes.each do |source|%>
        <%@target_attribute = @target_attributes.where("empid=?",source.empid)%>
        <%if @target_attribute.present?%>
            <%if source.attributes[params[:source_attribute]].to_f.to_s == source.attributes[params[:source_attribute]].to_f.to_s && @target_attribute.first.attributes[params[:target_attribute]].to_i.to_s == @target_attribute.first.attributes[params[:target_attribute]]%>
                <%if source.attributes[params[:source_attribute]] == @target_attribute.first.attributes[params[:target_attribute]].to_f.to_s%>
                    <tr>
                      <td><%=source.empid%></td>
                      <td><%=source.employeename%></td>
                      <td><%=source.attributes[params[:source_attribute]]%></td>
                      <%if @target_attribute.present?%>
                          <td><%=@target_attribute.first.attributes[params[:target_attribute]]%></td>
                      <%else%>
                          <td></td>
                      <%end%>
                    </tr>
                <%else%>
                    <tr style="background-color: beige">
                      <td><%=source.empid%></td>
                      <td><%=source.employeename%></td>
                      <td><%=source.attributes[params[:source_attribute]]%></td>
                      <%if @target_attribute.present?%>
                          <td><%=@target_attribute.first.attributes[params[:target_attribute]].to_f.to_s%></td>
                      <%else%>
                          <td></td>
                      <%end%>
                    </tr>
                <%end%>
            <%else%>
                <%if source.attributes[params[:source_attribute]] == @target_attribute.first.attributes[params[:target_attribute]]%>
                    <tr>
                      <td><%=source.empid%></td>
                      <td><%=source.employeename%></td>
                      <td><%=source.attributes[params[:source_attribute]]%></td>
                      <%if @target_attribute.present?%>
                          <td><%=@target_attribute.first.attributes[params[:target_attribute]]%></td>
                      <%else%>
                          <td></td>
                      <%end%>
                    </tr>
                <%else%>
                    <tr style="background-color: beige">
                      <td><%=source.empid%></td>
                      <td><%=source.employeename%></td>
                      <td><%=source.attributes[params[:source_attribute]]%></td>
                      <%if @target_attribute.present?%>
                          <td><%=@target_attribute.first.attributes[params[:target_attribute]]%></td>
                      <%else%>
                          <td></td>
                      <%end%>
                    </tr>
                <%end%>
            <%end%>
        <%end%>
    <%end%>
  </boby>
</table>

app/views/fileuploads/edit.html.erb
<h1>Editing Fileupload</h1>

<%= render 'form' %>

<%= link_to 'Show', @fileupload %> |
<%= link_to 'Back', fileuploads_path %>

app/views/fileuploads/find_attributes.html.erb
<script>
  $( document ).ready(function() {
    $("#proceed").click(function(){
      var source = $("#source :selected")[0].text;
      var target = $("#target :selected")[0].text;
      var source_attribute = $("#source_attribute :selected")[0].text;
      var target_attribute = $("#target_attribute :selected")[0].text;
      $.ajax({
        method: 'POST',
        url: '/fileuploads/compare',
        data: "source="+source+"&target="+target+"&source_attribute="+source_attribute+"&target_attribute="+target_attribute,
        dataType: 'html',
        statusCode: {

        }
      }).done(function(res){
        $("#table").empty();
        $("#table").show();
        $("#table").append(res);
        $("#attribute_filter").hide();
        $("#attribute_filter_show").show()
      });
    });
    $("#attribute_filter_show").click(function(){
      $("#attribute_filter").show();
      $("#attribute_filter_show").hide();
      $("#table").hide()
    });
  });
</script>
<br/>
<div id="attribute_filter" style="margin-left: 130px">
  <h3 style="margin-left: 220px">Select the attributes to be compared</h3>
  <div class="row">
    <div class="col-md-6">
      <p><%=params[:source]%></p>
      <select multiple style="width:200px; height:200px;" id="source_attribute">
        <%@source_attributes.each do |source_attribute|%>
          <%if source_attribute != "id" && !source_attribute.blank? %>
            <option text = <%="#{source_attribute}"%>><%="#{source_attribute}"%></option>
          <%end%>
      <%end%>
      </select>
    </div>
    <div class="col-md-6">
    <p><%=params[:target]%></p>
    <div class="col-md-3"></div>
      <select multiple style="width:200px; height:200px;" id="target_attribute">
        <%@target_attributes.each do |target_attribute|%>
          <%if target_attribute != "id" && !target_attribute.blank? %>
            <option text = <%="#{target_attribute}"%>><%="#{target_attribute}"%></option>
          <%end%>
        <%end%>
      </select>
    </div>
  </div>
  <br/>
  <div class="row">
    <div class = "col-md-5"></div>
    <input type="button" value="Proceed to Compare" class="btn btn-danger" id="proceed">
  </div>
</div>

<div id="table"></div>

app/views/fileuploads/index.html.erb
<script type="text/javascript" charset="utf-8">
  $( document ).ready(function() {
    $("#compare").click(function(){
      if ($("#source :selected")[0] == undefined){
        alert("Pleasee Select Source")
        return false
      }
      if ($("#target :selected")[0] == undefined){
        alert("Please Select Target")
        return false
      }
      var source = $("#source :selected")[0].value;
      var target = $("#target :selected")[0].value;
      $.ajax({
        method: 'POST',
        url: '/fileuploads/find_attributes',
        data: "source="+source+"&target="+target,
        dataType: 'html',
        statusCode: {

        }
      }).done(function(res){
        $("#attributes").empty();
        $("#attributes").show();
        $("#attributes").append(res);
        $("#file_select").hide();
        $("#file_filter_show").show()
        $("#table").hide()
      });
    });
    $("#file_filter_show").click(function(){
      $("#file_select").show();
      $("#file_filter_show").hide();
      $("#attribute_filter_show").hide()
      $("#table").hide()

    });
  });
</script>
<input type="button" value="Show Project Filter" id="file_filter_show" style="display:none" class="btn btn-info">
<input type="button" value="Show Attribute Filter" id="attribute_filter_show" style="display:none" class="btn btn-info">
<div  id="file_select">
  <h3 style="text-align: center">Compare Excel Sheets</h3>
  <div class="row">
    <div class="col-md-6">
      <h3 style="margin-left: 100px">Select The Source</h3>
      <div class="col-md-4"></div>
      <select multiple style="width:400px" id="source">
        <%@fileuploads.each do |file|%>
          <option value = <%="#{file.project_name.capitalize}"+"#{file.file_name.downcase}"%>><%="#{file.project_name.capitalize}"+"#{file.file_name.downcase}"%></option>
        <%end%>
      </select>
    </div>
    <div class="col-md-6">
      <h3 style="margin-left: 250px">Select the Target</h3>
      <div class="col-md-3"></div>
      <select multiple style="width:400px" id="target">
        <%@fileuploads.each do |file|%>
            <option value = <%="#{file.project_name.capitalize}"+"#{file.file_name.downcase}"%>><%="#{file.project_name.capitalize}"+"#{file.file_name.downcase}"%></option>
        <%end%>
      </select>
    </div>
  </div>
  <br/>
  <div class="row">
    <div class = "col-md-5"></div>
    <input type="Button" class="btn btn-success" value="Compare" style="margin-left:45px" id="compare">
  </div>
</div>
<div id="attributes"></div>

app/views/fileuploads/new.html.erb
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <h1 style="text-align: center">New Fileupload</h1>

    <%= form_tag '/fileuploads', multipart: true  do %>
        <div class="form-field">
          <%= label_tag :project_name %><br>
          <%= text_field_tag :project_name ,nil ,class:"form-control" , placehoder:"Enter the project name" %>
        </div>
        <div class="form-field">
          <%= label_tag :file_name %><br>
          <%= text_field_tag :file_name ,nil ,class:"form-control" ,placehoder:"Enter the file name" %>
        </div>
        <div class="form-field">
          <%= label_tag :start %><br>
          <%= text_field_tag :start ,nil ,class:"form-control" ,placehoder:"Enter the Start row" %>
        </div>
        <div class="form-field">
          <%= label_tag :end %><br>
          <%= text_field_tag :end ,nil ,class:"form-control" ,placehoder:"Enter the End row" %>
        </div>
        <div class="form-field">
          <%= label_tag :unique %><br>
          <%= text_field_tag :unique ,nil ,class:"form-control" ,placehoder:"Enter the unique column" %>
        </div>
        <div class="form-field">
          <%= label_tag :last_row %><br>
          <%= text_field_tag :last_row ,nil ,class:"form-control" ,placehoder:"Enter the last  column" %>
        </div>
        <div>
          <br/>
          <%=file_field_tag :excel_file%>
        </div>
        <br/>
        <div class="actions">
          <%= submit_tag "import" ,class:"btn btn-primary"%>
        </div>
    <% end %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FileUpload</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">
  <script src="//cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-9" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button> <a class="navbar-brand" href="#">Excel Compare</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-9">
      <ul class="nav navbar-nav">
        <li class="active"><%=link_to "Upload Files", new_fileupload_path%></li>
        <li><%=link_to "Compare Files", fileuploads_path%></li>
        <li><a href="#">Link</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <%= yield %>
</div>

</body>
</html>